export { default as HomePage } from './HomePage';
export { default as PageNotFound } from './PageNotFound';
export { default as Contact } from './Contact';
export { default as About } from './About';
export { default as Policy } from './Policy';
export { default as Cart } from './Cart';
export { default as Categories } from './Categories';
export { default as CategoryProducts } from './CategoryProducts';
export { default as Register } from './Auth/Register';
export { default as ForgotPassword } from './Auth/ForgotPassword';
export { default as Login } from './Auth/Login';
export { default as Dashboard } from './user/Dashboard';
export { default as AdminDashboard} from './Admin/AdminDashboard';
export { default as CreateProduct} from './Admin/CreateProduct';
export { default as CreateCategory} from './Admin/CreateCategory';
export { default as Users} from './Admin/Users';
export { default as Products} from './Admin/Products';
export { default as UpdateProduct} from './Admin/UpdateProduct';
